Even after pointing to the correct version of GHC HEAD, cassava does not work
╭─bollu@strangeattractor ~/work/asterius ‹may-16-improve-ghc-testsuite-error-reporting*›
╰─$ stack test asterius:ghc-testsuite
WARNING: Ignoring out of range dependency (allow-newer enabled): base-4.13.0.0. hashable requires: >=4.4 && <4.13
WARNING: Ignoring out of range dependency (allow-newer enabled): base-4.13.0.0. integer-logarithms requires: >=4.3 && <4.13
WARNING: Ignoring out of range dependency (allow-newer enabled): ghc-prim-0.6.1. integer-logarithms requires: <0.6
WARNING: Ignoring out of range dependency (allow-newer enabled): base-4.13.0.0. primitive requires: >=4.5 && <4.12
WARNING: Ignoring out of range dependency (allow-newer enabled): ghc-prim-0.6.1. primitive requires: >=0.2 && <0.6
WARNING: Ignoring out of range dependency (allow-newer enabled): ghc-prim-0.6.1. aeson requires: >=0.2 && <0.6
WARNING: Ignoring out of range dependency (allow-newer enabled): template-haskell-2.15.0.0. aeson requires: >=2.7.0.0 && <2.15
WARNING: Ignoring out of range dependency (allow-newer enabled): time-1.9.2. aeson requires: >=1.4 && <1.9
WARNING: Ignoring out of range dependency (allow-newer enabled): time-1.9.2. time-locale-compat requires: <1.5
WARNING: Ignoring out of range dependency (allow-newer enabled): ghc-prim-0.6.1. vector requires: >=0.2 && <0.6
WARNING: Ignoring out of range dependency (allow-newer enabled): bytestring-0.10.9.0. cassava requires: >=0.9.2 && <0.10.4
WARNING: Ignoring out of range dependency (allow-newer enabled): containers-0.6.0.1. cassava requires: >=0.4.2 && <0.6
WARNING: Ignoring out of range dependency (allow-newer enabled): base-4.13.0.0. async requires: >=4.3 && <4.13
WARNING: Ignoring out of range dependency (allow-newer enabled): transformers-0.5.6.2. transformers-compat requires: >=0.3 && ==0.2.*
WARNING: Ignoring out of range dependency (allow-newer enabled): base-4.13.0.0. splitmix requires: >=4.3 && <4.13
WARNING: Ignoring out of range dependency (allow-newer enabled): time-1.9.2. splitmix requires: >=1.2.0.3 && <1.9
WARNING: Ignoring out of range dependency (allow-newer enabled): base-4.13.0.0. tasty-hspec requires: ^>=4.9 || ^>=4.10 || ^>=4.11 || ^>=4.12
WARNING: Ignoring out of range dependency (allow-newer enabled): QuickCheck-2.13.1. hspec-core requires: ==2.12.*
cassava-0.5.1.0: build (lib)
Progress 1/3

--  While building package cassava-0.5.1.0 using:
      /home/bollu/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_3.0.0.0_ghc-8.9.20190403 --builddir=.stack-work/dist/x86_64-linux/Cabal-3.0.0.0 build lib:cassava --ghc-options " -ddump-hi -ddump-to-file -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
    Logs have been written to: /home/bollu/work/asterius/.stack-work/logs/cassava-0.5.1.0.log

    /home/bollu/.stack/programs/x86_64-linux/ghc-8.9.20190403/lib/ghc-8.9.20190403/bin/ghc-pkg: /lib/libtinfo.so.6: no version information available (required by /home/bollu/.stack/programs/x86_64-linux/ghc-8.9.20190403/lib/ghc-8.9.20190403/bin/ghc-pkg)
    Preprocessing library for cassava-0.5.1.0..
    Building library for cassava-0.5.1.0..
    /home/bollu/.stack/programs/x86_64-linux/ghc-8.9.20190403/lib/ghc-8.9.20190403/bin/ghc: /lib/libtinfo.so.6: no version information available (required by /home/bollu/.stack/programs/x86_64-linux/ghc-8.9.20190403/lib/ghc-8.9.20190403/bin/ghc)

    on the commandline: warning:
        -Wnoncanonical-monadfail-instances is deprecated: fail is no longer a method of Monad

    /home/bollu/work/asterius/.stack-work/downloaded/0TZV1j_OyWRA/cassava-0.5.1.0/Data/Csv/Conversion.hs:26:3: error:
         error: #error **INVARIANT BROKEN** Detected invalid combination of `text-short` and `bytestring` versions. Please verify the `pre-bytestring-0.10-4` flag-logic in the .cabal file wasn't elided.
         # error **INVARIANT BROKEN** Detected invalid combination of `text-short` and `bytestring` versions. Please verify the `pre-bytestring-0.10-4` flag-logic in the .cabal file wasn't elided.
           ^~~~~
       |
    26 | # error **INVARIANT BROKEN** Detected invalid combination of `text-short` and `bytestring` versions. Please verify the `pre-bytestring-0.10-4` flag-logic in the .cabal file wasn't elided.
       |   ^

    /home/bollu/work/asterius/.stack-work/downloaded/0TZV1j_OyWRA/cassava-0.5.1.0/Data/Csv/Conversion.hs:99:0: error:
         warning: "MIN_VERSION_text_short" is not defined, evaluates to 0 [-Wundef]
         #if MIN_VERSION_text_short(0,1,0)

       |
    99 | #if MIN_VERSION_text_short(0,1,0)
       | ^

    /home/bollu/work/asterius/.stack-work/downloaded/0TZV1j_OyWRA/cassava-0.5.1.0/Data/Csv/Conversion.hs:99:0: error:
         error: missing binary operator before token "("
       |
    99 | #if MIN_VERSION_text_short(0,1,0)
       | ^

    /home/bollu/work/asterius/.stack-work/downloaded/0TZV1j_OyWRA/cassava-0.5.1.0/Data/Csv/Conversion.hs:1010:0: error:
         warning: "MIN_VERSION_text_short" is not defined, evaluates to 0 [-Wundef]
         #if MIN_VERSION_text_short(0,1,0)

         |
    1010 | #if MIN_VERSION_text_short(0,1,0)
         | ^

    /home/bollu/work/asterius/.stack-work/downloaded/0TZV1j_OyWRA/cassava-0.5.1.0/Data/Csv/Conversion.hs:1010:0: error:
         error: missing binary operator before token "("
         |
    1010 | #if MIN_VERSION_text_short(0,1,0)
         | ^
    `gcc' failed in phase `C pre-processor'. (Exit code: 1)